name: Auto Tag and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_tag_and_release:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Create new tag based on current date and time
      run: |
        NEW_TAG=$(date +'%y%m%d-%H%M')
        echo "Created new tag: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        git tag $NEW_TAG

    - name: Update Version in NemUpgradeTracker.toc
      run: |
        sed -i "s/^## Version: .*/## Version: $NEW_TAG/" NemUpgradeTracker.toc
        echo "Updated NemUpgradeTracker.toc with version: $NEW_TAG"
      env:
        NEW_TAG: ${{ env.NEW_TAG }}

    - name: Commit and Push changes to .toc file
      run: |
        git add NemUpgradeTracker.toc
        git commit -m "Update version in NemUpgradeTracker.toc to $NEW_TAG" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEW_TAG: ${{ env.NEW_TAG }}

    - name: Push new tag to GitHub
      run: |
        git push origin $NEW_TAG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEW_TAG: ${{ env.NEW_TAG }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.NEW_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 